#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 1 -yoffset 32 -line-padding 4 -columns 1 -width 25 -lines 10 -padding 10 -hide-scrollbar -show-icons -drun-icon-theme "Papirus" -font "Fantasque Sans Mono 10"
